# Generated by Django 3.2.9 on 2021-11-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.CharField(max_length=200)),
                ('fechainicio', models.DateTimeField()),
                ('fechafin', models.DateTimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.curso')),
            ],
        ),
    ]
